# Powerline Theme Config
#
# https://github.com/bhilburn/powerlevel9k#prompt-customization
#
# Nerd fonts https://github.com/ryanoasis/nerd-fonts

POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time time mise context background_jobs custom_tmux)
# Context
DEFAULT_USER=$USER

# Dir
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=''

POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"

# Vi_mode
POWERLEVEL9K_VI_INSERT_MODE_STRING=">"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="<"
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND="clear"
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND="clear"

# ruby
POWERLEVEL9K_CHRUBY_BACKGROUND='clear'
POWERLEVEL9K_CHRUBY_FOREGROUND='red'
POWERLEVEL9K_CHRUBY_BACKGROUND='clear'

# Node and NVM
POWERLEVEL9K_NODE_VERSION_BACKGROUND='clear'
POWERLEVEL9K_NODE_VERSION_FOREGROUND='green'

# Python
POWERLEVEL9K_PYENV_BACKGROUND='clear'
POWERLEVEL9K_PYENV_FOREGROUND='106'
POWERLEVEL9K_PYTHON_ICON='\ue606'

# VCS
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="clear"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="magenta"

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="clear"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"

POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="clear"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"

POWERLEVEL9K_VCS_BACKGROUND="clear"
POWERLEVEL9K_VCS_FOREGROUND="grey"

# root_indicator
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white"
POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

# Time
POWERLEVEL9K_TIME_BACKGROUND="clear"
POWERLEVEL9K_TIME_FOREGROUND="cyan"

# Execution Time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta'

# Background Jobs
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green'

# General Styles
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{white}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} "

function prompt_mise() {
    local plugins=("${(@f)$(mise ls --current 2>/dev/null | awk '!/\(symlink\)/ && $3!="~/.tool-versions" && $3!="~/.config/mise/config.toml" {print $1, $2, $3}')}")
    local plugin
    for plugin in ${(k)plugins}; do
      local parts=("${(@s/ /)plugin}")
      local tool=${(U)parts[1]}
      local version=${parts[2]}
      local missing=${parts[3]}
     if [[ "$missing"  == "(missing)" ]]; then
          p10k segment  -r -i "${tool}_ICON" -s $tool -t "%B%U$version (missing)%b%u"
      else
          p10k segment -r -i "${tool}_ICON" -s $tool -t "$version"
      fi
    done
  }

  # Colors
  typeset -g POWERLEVEL9K_MISE_BACKGROUND='clear'

  typeset -g POWERLEVEL9K_MISE_DOTNET_CORE_FOREGROUND=5
  typeset -g POWERLEVEL9K_MISE_ELIXIR_FOREGROUND=5
  typeset -g POWERLEVEL9K_MISE_ERLANG_FOREGROUND=1
  typeset -g POWERLEVEL9K_MISE_FLUTTER_FOREGROUND=4
  typeset -g POWERLEVEL9K_MISE_GOLANG_FOREGROUND=4
  typeset -g POWERLEVEL9K_MISE_HASKELL_FOREGROUND=3
  typeset -g POWERLEVEL9K_MISE_JAVA_FOREGROUND=7
  typeset -g POWERLEVEL9K_MISE_JULIA_FOREGROUND=2
  typeset -g POWERLEVEL9K_MISE_LUA_FOREGROUND=4
  typeset -g POWERLEVEL9K_MISE_NODE_FOREGROUND=2
  typeset -g POWERLEVEL9K_MISE_PERL_FOREGROUND=4
  typeset -g POWERLEVEL9K_MISE_PHP_FOREGROUND=5
  typeset -g POWERLEVEL9K_MISE_POSTGRES_FOREGROUND=6
  typeset -g POWERLEVEL9K_MISE_PYTHON_FOREGROUND=4
  typeset -g POWERLEVEL9K_MISE_RUBY_FOREGROUND=1
  typeset -g POWERLEVEL9K_MISE_RUST_FOREGROUND=208

  # Substitute the default asdf prompt element
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=("${POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS[@]/asdf/mise}")
