# ZShell Configuration
#
# This .zshrc file is managed by the antibody plugin manager and is purposly
# kept modular.

export DOTFILES="$HOME/.dotfiles"
export ZSH_CONFIG="$HOME/.zshrc.d"

source "$ZSH_CONFIG/init.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

