# ZShell Configuration
#
# This .zshrc file is managed by the antibody plugin manager and is purposly
# kept modular.

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# End P10K Instant Prompt

export DOTFILES="$HOME/.dotfiles"
export ZSH_CONFIG="$HOME/.zshrc.d"

source "$ZSH_CONFIG/init.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


iterm2_print_user_vars() {
  iterm2_set_user_var gitBranch $((git branch 2> /dev/null) | grep \* | cut -c3-)
  iterm2_set_user_var ruby_version $(echo $RUBY_VERSION)
  iterm2_set_user_var ruby_icon $(echo "\uF219")
}

