#!/usr/bin/ruby --disable-gems

module ProtectedBranch
  extend self
  DEFAULT_BRANCHES = 'master main development production'
  PROTECTED_BRANCHES = ENV.fetch('GIT_PROTECTED_BRANCHES', DEFAULT_BRANCHES ).split(' ')
  def main
    if PROTECTED_BRANCHES.include?(current_branch)
      reject!("You're about to commit to protected branch: \033[0;31m#{current_branch}\033[0m. Is that what you intended to do?")
    end
  end

  private

  def current_branch
    `git branch --show-current`.chomp
  end

  def reject!(message)
    STDERR.puts message
    STDERR.puts "If you still want to commit, you can ignore the pre_commit git hook by adding  \x1b[32m\--no-verify\x1b[0m to your command."
    exit(1)
  end
end

ProtectedBranch.main
