#!/usr/bin/env zsh
source ~/.zshrc

# bundle and statically source all the plugins listed in $ZSH_CONFIG/antibody/plugins.txt
antibody static

ln -s ~/.zshrc.d ~/.dotfiles/tag-zshrc.d

# if [ -d ~/.cron_jobs/LaunchAgents ]; then
#   echo "Symlinking ~/.cron_jobs/LaunchAgents to ~/Library/LaunchAgents/"
#   ln -s ~/.cron_jobs/LaunchAgents/* ~/Library/LaunchAgents/
# fi

# run install script for each tag if necessary
source ~/rcrc
for tag in $TAGS; do
    tag=$(echo "$tag" | tr -d '[:space:]')  # Remove leading/trailing whitespaces
    local install_script="$DOTFILES/tag-$tag/install.sh"

    if [ -f install_script ]; then
        echo "Running $install_script"
        sh "$install_script"
    fi
done

