# ZShell Configuration
# Host: Magi-06.local
#
# This .zshrc file is managed by the antibody plugin manager and is purposly
# kept modular.

export DOTFILES="$HOME/.dotfiles"
export ZSH_CONFIG="$DOTFILES/zshrc.d"

source "$ZSH_CONFIG/init.zsh"
